# Make it easy to get to tmux commands
unbind C-b
set-option -g prefix C-w
bind-key C-w send-prefix

# Enable mouse mode to make things easy
set -g mouse on

# Easy to split windows
bind r split-window -v
bind c split-window -h
unbind '"'
unbind %

# Easy to navigate windows
bind -r f select-pane -D
bind -r d select-pane -U
bind -r s select-pane -L
bind -r g select-pane -R

# Get appropriate plugins
set -g @plugin 'tmux-plugins/tmp'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Tokyo Night and config
set -g @plugin "janoamaral/tokyo-night-tmux"

set -g @tokyo-night-tmux_theme "storm"

set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_path_format full

set -g @tokyo-night-tmux_show_hostname 1

set -g @tokyo-night-tmux_show_netspeed 1
#set -g @tokyo-night-tmux_netspeed_iface "default" # Detected via default route
#set -g @tokyo-night-tmux_netspeed_showip 1      # Display IPv4 address (default 0)
#set -g @tokyo-night-tmux_netspeed_refresh 1     # Update interval in seconds (default 1)

# Do package initialization
run '~/.config/tmux/plugins/tpm/tpm'
